### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by ogezue** [pmusolino/PMAlertController#63]
Is it possible to add custom buttons like this?
<img width="363" alt="button" src="https://user-images.githubusercontent.com/2361031/39085317-f5322508-4580-11e8-82fd-6ee874316a1d.png">

**Comment by pmusolino** [comment]
Yes, you can customize the button to appear like this.

-Paolo

**Comment by JawaharChirimar** [comment]
How do you do it? Would appreciate it if you can point me in the right direction?

**Comment by silnose** [comment]
any update of this ?

> How do you do it? Would appreciate it if you can point me in the right direction?

Help with the same! haha

**Comment by silnose** [comment]
I try with a image of the button and this configuration

```
        okAction.setImage(image, for: .normal)
        okAction.imageEdgeInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: -50)
        okAction.titleEdgeInsets = UIEdgeInsets(top: 0, left: -200, bottom: 0, right: 0)
```

![Screen Shot 2019-07-03 at 00 43 27](https://user-images.githubusercontent.com/10604773/60561891-a17d2a80-9d2b-11e9-8395-fc125453c003.png)


I don't know if is the best approach but i try to set the image as background and i can't make look right, it's getting to big and very stretched


`okAction.setBackgroundImage(image, for: .normal)
`

![image](https://user-images.githubusercontent.com/10604773/60562087-7a732880-9d2c-11e9-8824-d150d77dd81d.png)

And I tried with gradient too but nothing happend , only the textButton  display :( 

I really appreciate some help here!. Thk in advance ;)
