### ISSUE TITLE
Change disappear animation to fade out

### ISSUE THREAD

**Issue by vsg24** [pmusolino/PMAlertController#64]
Hi,

I love this project however the disappearing animation does not suit my app. I need to change it to something like a fade out (or something else really). I could'n find any way to achieve this. Please help (Some example code would be appreciated)

**Comment by pmusolino** [comment]
Hi @VSG24,

currently is not possible to change the animation, but is a good improvement for a next version.

If you think you have a valid and dynamic solution, implement it and open a pull request, please. Otherwise, you can fork the project and implement your fade out animation.

Thanks
-Paolo

**Comment by VSG24** [comment]
Thanks for your response. I want to fork the project and change the animation myself but I'm not sure where the code for anination exists. Can you point me to the right direction?

**Comment by Daksh14** [comment]
Hello, if someone wants to disable the gravity animation do
```swift
let alertVC = PMAlertController(title: "Options", description: nil, image: nil, style: .alert)
alertVC.gravityDismissAnimation = false // this here
```
