### ISSUE TITLE
Add spinner or rotating images

### ISSUE THREAD

**Issue by bjimenezned** [pmusolino/PMAlertController#66]
It would be cool if the alertcontroller had the ability to rotate images or a native spinner option to offer feedback on lengthy tasks,
In the meanwhile I'll try to make my own with QuartzCore and add it as a pull request

**Comment by pmusolino** [comment]
HI @bjimenezned.
Please read the readme file, there are some example on how to use the "loader" feature.

Thanks
Paolo
