### ISSUE TITLE
Feature Request: Dim background while presenting PMAlert

### ISSUE THREAD

**Issue by sandeepbol** [pmusolino/PMAlertController#67]
I tried using a different alertMaskBackground image but that didn't work for me in dismissWithBackgroudTouch = true mode. Can you suggest workaround for it or implement it in future release?

**Comment by pmusolino** [comment]
What is the final result that you expect?

**Comment by sandeepbol** [comment]
in dismissWithBackgroundTouch mode enabled, there should be an option to dim the background (a custom UIView() layer behind the alert)?

**Comment by pmusolino** [comment]
So you want to hide what you see behind the alert? In this case, you can use the UIImageView called `alertMaskBackground`.

**Comment by sandeepbol** [comment]
I write in the original question, alertMaskBackground didn't work for me.

**Comment by pmusolino** [comment]
I tried to set a background image

```
alertVC.alertMaskBackground.image = UIImage(named: "myImage.png")
alertVC.dismissWithBackgroudTouch = true
```

and it worked! 👍

**Comment by sandeepbol** [comment]
Thanks a lot buddy. I will give it an another try as you suggested and it should work. Let me get back to you with my findings asap. Then we can close the ticket. Thanks again for your help :)
