### ISSUE TITLE
Invalid Task Error after Pod Install

### ISSUE THREAD

**Issue by danielshaffer** [pmusolino/PMAlertController#78]
I just installed the Pod and when I built the project I got 3 errors saying Invalid Task Strip Nib. I had to go to Build Phases and remove the PMAlertViewController.xib, and then it worked. Not sure if anyone else ran into this, but hopefully this is fixed in a future version. 

I'm running Xcode 10.1.

Thanks,
Daniel

**Comment by pmusolino** [comment]
Hi @danielshaffer! This is the first time that I heard about this problem. Do you run `pod repo update` before pod install? What version of PMAlertController do you installed?

**Comment by danielshaffer** [comment]
Hi,

I simply added “pod PMAlertController” in the pod file, and then “Pod Install” in terminal. It’s the latest version, 3.5.0. I’ve never run into an issue like this before. 

Thanks,
Daniel

**Comment by pmusolino** [comment]
Can you try to remove and re-install it?

**Comment by MartinP7r** [comment]
I get the same error when installing pods without `use_frameworks!`.   
@danielshaffer could you confirm whether or not you're using 'use_frameworks!' for your swift pods?  
Though I think that cocoapods should tell you at installation time about it, if one or more of the pods don't support static libraries yet, but at least it works for me.

**Comment by pmusolino** [comment]
`use_frameworks!` tells CocoaPods that you want to use Frameworks instead of Static Libraries. Since Swift does not support Static Libraries you have to use frameworks.

**Comment by MartinP7r** [comment]
cocoapods supports static swift libraries since 1.5.0 http://blog.cocoapods.org/CocoaPods-1.5.0

**Comment by Patrick3131** [comment]
I am having the same problem. 
This describes my problem: https://stackoverflow.com/questions/40480503/the-bundle-uitests-couldn-t-be-loaded-because-it-is-damaged-or-missing-necessary

but when I want to follow the presented solution from stackoverflow I get the same problem as @danielshaffer .

Any solutions? Thanks!
