### ISSUE TITLE
Swift Compiler Error in Swift 5

### ISSUE THREAD

**Issue by iamchenchen** [pmusolino/PMAlertController#89]
I'm using XCode Version 10.2.1 (10E1001) with Swift 5
Using Cocoapod with PMAlertController (4.0.0)

<img width="267" alt="Screen Shot 2019-06-18 at 6 15 02 PM" src="https://user-images.githubusercontent.com/808905/59729916-44468c80-91f5-11e9-9304-372e3e8a47f5.png">

**Comment by pmusolino** [comment]
This is really strange. Are you sure that you installed the right version? Try to call `pod repo update` before pod install or pod update and let me know.

**Comment by iamchenchen** [comment]
looks like it could be a compiler issue, I updated to Catalina beta 2 and restarted, everything looks fine now. Thanks!
